#pragma once
#include <Arduino.h>
#include <memory>

/**
 * @brief Generate the bash script served to curl clients requesting /main
 *
 * @param host The hostname or IP address of the ESP32
 * @param otaKey The OTA gate key string
 * @return String Containing the bash interactive dashboard script
 */
inline String generateCurlDashboardScript(const String &host, const char *otaKey) {
  const size_t n = 4600;
  std::unique_ptr<char[]> buf(new char[n]);
  snprintf(buf.get(), n,
    "#!/bin/bash\n"
    "HOST=\"%s\"\n"
    "OTAKEY=\"%s\"\n"
    "while true; do\n"
    "  clear\n"
    "  LIVE=$(curl -s http://$HOST/api/live 2>/dev/null)\n"
    "  OTA_ON=$(echo \"$LIVE\" | grep -o '\"ota\":[01]' | cut -d: -f2)\n"
    "  if [[ -z \"$OTA_ON\" ]]; then OTA_ON=\"0\"; fi\n"
    "  CAL_ON=$(echo \"$LIVE\" | grep -o '\"cal\":[01]' | cut -d: -f2)\n"
    "  if [[ -z \"$CAL_ON\" ]]; then CAL_ON=\"0\"; fi\n"
    "  echo -e '\\n=== SwitchBot Dashboard ==='\n"
    "  if [[ \"$CAL_ON\" == \"1\" ]]; then\n"
    "    echo ' [1] Trigger Servo'\n"
    "  else\n"
    "    echo ' [1] Calibrate Servo'\n"
    "  fi\n"
    "  echo ' [2] Device Info'\n"
    "  echo ' [3] Logs & Debug'\n"
    "  echo ' [C] Clear Logs'\n"
    "  if [[ \"$OTA_ON\" == \"1\" ]]; then\n"
    "    echo ' [O] Disable OTA'\n"
    "  else\n"
    "    echo ' [O] Enable OTA'\n"
    "  fi\n"
    "  echo ' [R] Reboot ESP32'\n"
    "  if [[ \"$CAL_ON\" == \"1\" ]]; then\n"
    "    echo ' [S] Recalibrate Servo'\n"
    "  fi\n"
    "  echo ' [X] Exit'\n"
    "  echo ''\n"
    "  opt=\"\"\n"
    "  read -n 1 -s -p 'Select an option: ' opt </dev/tty\n"
    "  echo ''\n"
    "  if [[ \"$opt\" == \"x\" || \"$opt\" == \"X\" ]]; then echo \"Exiting.\"; break; fi\n"
    "  if [[ \"$opt\" == \"1\" ]]; then\n"
    "    if [[ \"$CAL_ON\" == \"1\" ]]; then\n"
    "      curl -s http://$HOST/\n"
    "      sleep 1.5\n"
    "    else\n"
    "      bash <(curl -s http://$HOST/calibrate)\n"
    "    fi\n"
    "  elif [[ \"$opt\" == \"s\" || \"$opt\" == \"S\" ]]; then\n"
    "    bash <(curl -s http://$HOST/calibrate)\n"
    "  elif [[ \"$opt\" == \"2\" ]]; then\n"
    "    clear\n"
    "    while true; do\n"
    "      OUT=$(curl -s http://$HOST/info)\n"
    "      echo -ne \"\\033[2J\\033[H$OUT\\n\\n [B] Back  |  [R] Reboot  |  [X] Exit\\033[K\\n\"\n"
    "      key=\"\"\n"
    "      read -t 1 -n 1 -s key </dev/tty\n"
    "      if [[ \"$key\" == \"b\" || \"$key\" == \"B\" ]]; then break; fi\n"
    "      if [[ \"$key\" == \"x\" || \"$key\" == \"X\" ]]; then echo \"\"; exit 0; fi\n"
    "      if [[ \"$key\" == \"r\" || \"$key\" == \"R\" ]]; then curl -X POST -s http://$HOST/reboot; exit 0; fi\n"
    "    done\n"
    "  elif [[ \"$opt\" == \"3\" ]]; then\n"
    "    while true; do\n"
    "      clear\n"
    "      OUT=$(curl -s http://$HOST/debug)\n"
    "      LIVE_SUB=$(curl -s http://$HOST/api/live 2>/dev/null)\n"
    "      OTA_SUB=$(echo \"$LIVE_SUB\" | grep -o '\"ota\":[01]' | cut -d: -f2)\n"
    "      if [[ \"$OTA_SUB\" == \"1\" ]]; then\n"
    "        OTA_LBL=\"[O] Disable OTA\"\n"
    "      else\n"
    "        OTA_LBL=\"[O] Enable OTA\"\n"
    "      fi\n"
    "      CAL_SUB=$(echo \"$LIVE_SUB\" | grep -o '\"cal\":[01]' | cut -d: -f2)\n"
    "      if [[ \"$CAL_SUB\" == \"1\" ]]; then\n"
    "        CAL_SUB_LBL=\" | [S] Recalibrate\"\n"
    "      else\n"
    "        CAL_SUB_LBL=\"\"\n"
    "      fi\n"
    "      echo \"$OUT\"\n"
    "      echo \"\"\n"
    "      echo -e \" [Enter] Refresh  | [B] Back    | [X] Exit\"\n"
    "      echo -e \" [C] Clear Logs   | [R] Reboot$CAL_SUB_LBL  | $OTA_LBL\"\n"
    "      key=\"\"\n"
    "      read -n 1 -s key </dev/tty\n"
    "      if [[ \"$key\" == \"b\" || \"$key\" == \"B\" ]]; then break; fi\n"
    "      if [[ \"$key\" == \"x\" || \"$key\" == \"X\" ]]; then echo \"\"; exit 0; fi\n"
    "      if [[ \"$key\" == \"r\" || \"$key\" == \"R\" ]]; then curl -X POST -s http://$HOST/reboot; exit 0; fi\n"
    "      if [[ \"$key\" == \"s\" || \"$key\" == \"S\" ]]; then\n"
    "        bash <(curl -s http://$HOST/calibrate)\n"
    "      fi\n"
    "      if [[ \"$key\" == \"c\" || \"$key\" == \"C\" ]]; then\n"
    "        curl -X POST -s http://$HOST/clear-logs\n"
    "        sleep 1\n"
    "      fi\n"
    "      if [[ \"$key\" == \"o\" || \"$key\" == \"O\" ]]; then\n"
    "        if [[ \"$OTA_SUB\" == \"1\" ]]; then\n"
    "          curl -X POST -s http://$HOST/ota/disable\n"
    "          echo 'OTA Disabled.'\n"
    "        else\n"
    "          curl -X POST -s http://$HOST/ota/enable -d \"key=$OTAKEY\"\n"
    "          echo 'OTA Enabled.'\n"
    "        fi\n"
    "        sleep 1\n"
    "      fi\n"
    "    done\n"
    "  elif [[ \"$opt\" == \"c\" || \"$opt\" == \"C\" ]]; then\n"
    "    curl -X POST -s http://$HOST/clear-logs\n"
    "    sleep 1.5\n"
    "  elif [[ \"$opt\" == \"o\" || \"$opt\" == \"O\" ]]; then\n"
    "    if [[ \"$OTA_ON\" == \"1\" ]]; then\n"
    "      curl -X POST -s http://$HOST/ota/disable\n"
    "      echo 'OTA Disabled.'\n"
    "    else\n"
    "      curl -X POST -s http://$HOST/ota/enable -d \"key=$OTAKEY\"\n"
    "      echo 'OTA Enabled.'\n"
    "    fi\n"
    "    sleep 1.5\n"
    "  elif [[ \"$opt\" == \"r\" || \"$opt\" == \"R\" ]]; then\n"
    "    curl -X POST -s http://$HOST/reboot\n"
    "    exit 0\n"
    "  fi\n"
    "done\n",
    host.c_str(), otaKey
  );
  return String(buf.get());
}
