#pragma once
#include <Arduino.h>
#include <memory>

/**
 * @brief Generate the bash script served to curl clients requesting /main
 *
 * @param host The hostname or IP address of the ESP32
 * @param otaKey The OTA gate key string
 * @return String Containing the bash interactive dashboard script
 */
// Generates the interactive terminal dashboard script streamed to curl users
inline String generateCurlDashboardScript(const String &host, const char *otaKey) {
  const size_t n = 4800;
  std::unique_ptr<char[]> buf(new char[n]);
  // Check if an OTA password was set so we know whether to ask for one
  int hasKey = (otaKey != nullptr && otaKey[0] != '\0') ? 1 : 0;
  snprintf(buf.get(), n,
    "#!/bin/bash\n"
    "HOST=\"%s\"\n"
    "HAS_OTAKEY=%d\n"
    "# Function to prompt for password and unlock wireless updates for 10 minutes\n"
    "do_enable_ota() {\n"
    "  if [[ \"$HAS_OTAKEY\" == \"1\" ]]; then\n"
    "    echo ''\n"
    "    # Wait for the user to type their key on the physical keyboard\n"
    "    read -s -p 'Enter OTA Key: ' ota_k </dev/tty\n"
    "    echo ''\n"
    "    RESP=$(curl -s -w '%%{http_code}' -o /dev/null -X POST http://$HOST/ota/enable -d \"key=$ota_k\")\n"
    "    if [[ \"$RESP\" == \"302\" || \"$RESP\" == \"200\" ]]; then\n"
    "      echo 'OTA Enabled (10 min).'\n"
    "    else\n"
    "      echo 'Invalid OTA Key.'\n"
    "    fi\n"
    "  else\n"
    "    curl -X POST -s http://$HOST/ota/enable\n"
    "    echo 'OTA Enabled (10 min).'\n"
    "  fi\n"
    "  sleep 1.5\n"
    "}\n"
    "# Main dashboard loop: shows options and listens for single keystrokes\n"
    "while true; do\n"
    "  clear\n"
    "  LIVE=$(curl -s http://$HOST/api/live 2>/dev/null)\n"
    "  OTA_ON=$(echo \"$LIVE\" | grep -o '\"ota\":[01]' | cut -d: -f2)\n"
    "  if [[ -z \"$OTA_ON\" ]]; then OTA_ON=\"0\"; fi\n"
    "  CAL_ON=$(echo \"$LIVE\" | grep -o '\"cal\":[01]' | cut -d: -f2)\n"
    "  if [[ -z \"$CAL_ON\" ]]; then CAL_ON=\"0\"; fi\n"
    "  echo -e '\\n=== SwitchBot Dashboard ==='\n"
    "  if [[ \"$CAL_ON\" == \"1\" ]]; then\n"
    "    echo ' [1] Trigger Servo'\n"
    "  else\n"
    "    echo ' [1] Calibrate Servo'\n"
    "  fi\n"
    "  echo ' [2] Device Info'\n"
    "  echo ' [3] Logs & Debug'\n"
    "  echo ' [C] Clear Logs'\n"
    "  if [[ \"$OTA_ON\" == \"1\" ]]; then\n"
    "    echo ' [O] Disable OTA'\n"
    "  else\n"
    "    echo ' [O] Enable OTA'\n"
    "  fi\n"
    "  echo ' [R] Reboot ESP32'\n"
    "  if [[ \"$CAL_ON\" == \"1\" ]]; then\n"
    "    echo ' [S] Recalibrate Servo'\n"
    "  fi\n"
    "  echo ' [X] Exit'\n"
    "  echo ''\n"
    "  opt=\"\"\n"
    "  read -n 1 -s -p 'Select an option: ' opt </dev/tty\n"
    "  echo ''\n"
    "  if [[ \"$opt\" == \"x\" || \"$opt\" == \"X\" ]]; then echo \"Exiting.\"; break; fi\n"
    "  if [[ \"$opt\" == \"1\" ]]; then\n"
    "    if [[ \"$CAL_ON\" == \"1\" ]]; then\n"
    "      curl -s http://$HOST/\n"
    "      sleep 1.5\n"
    "    else\n"
    "      bash <(curl -s http://$HOST/calibrate)\n"
    "    fi\n"
    "  elif [[ \"$opt\" == \"s\" || \"$opt\" == \"S\" ]]; then\n"
    "    bash <(curl -s http://$HOST/calibrate)\n"
    "  elif [[ \"$opt\" == \"2\" ]]; then\n"
    "    clear\n"
    "    while true; do\n"
    "      OUT=$(curl -s http://$HOST/info)\n"
    "      echo -ne \"\\033[2J\\033[H$OUT\\n\\n [B] Back  |  [R] Reboot  |  [X] Exit\\033[K\\n\"\n"
    "      key=\"\"\n"
    "      read -t 1 -n 1 -s key </dev/tty\n"
    "      if [[ \"$key\" == \"b\" || \"$key\" == \"B\" ]]; then break; fi\n"
    "      if [[ \"$key\" == \"x\" || \"$key\" == \"X\" ]]; then echo \"\"; exit 0; fi\n"
    "      if [[ \"$key\" == \"r\" || \"$key\" == \"R\" ]]; then curl -X POST -s http://$HOST/reboot; exit 0; fi\n"
    "    done\n"
    "  elif [[ \"$opt\" == \"3\" ]]; then\n"
    "    while true; do\n"
    "      clear\n"
    "      OUT=$(curl -s http://$HOST/debug)\n"
    "      if echo \"$OUT\" | grep -q 'OTA Status.*Enabled'; then\n"
    "        OTA_LBL=\"[O] Disable OTA\"\n"
    "        OTA_SUB=\"1\"\n"
    "      else\n"
    "        OTA_LBL=\"[O] Enable OTA\"\n"
    "        OTA_SUB=\"0\"\n"
    "      fi\n"
    "      if [[ \"$CAL_ON\" == \"1\" ]]; then\n"
    "        CAL_LINE=\" [S] Recalibrate\"\n"
    "      else\n"
    "        CAL_LINE=\"\"\n"
    "      fi\n"
    "      echo \"$OUT\"\n"
    "      echo \"\"\n"
    "      echo -e \" [Enter] Refresh  | [B] Back    | [X] Exit\"\n"
    "      echo -e \" [C] Clear Logs   | [R] Reboot  | $OTA_LBL\"\n"
    "      if [[ -n \"$CAL_LINE\" ]]; then echo -e \"$CAL_LINE\"; fi\n"
    "      key=\"\"\n"
    "      read -n 1 -s key </dev/tty\n"
    "      if [[ \"$key\" == \"b\" || \"$key\" == \"B\" ]]; then break; fi\n"
    "      if [[ \"$key\" == \"x\" || \"$key\" == \"X\" ]]; then echo \"\"; exit 0; fi\n"
    "      if [[ \"$key\" == \"r\" || \"$key\" == \"R\" ]]; then curl -X POST -s http://$HOST/reboot; exit 0; fi\n"
    "      if [[ \"$key\" == \"s\" || \"$key\" == \"S\" ]]; then\n"
    "        bash <(curl -s http://$HOST/calibrate)\n"
    "      fi\n"
    "      if [[ \"$key\" == \"c\" || \"$key\" == \"C\" ]]; then\n"
    "        curl -X POST -s http://$HOST/clear-logs\n"
    "        sleep 1\n"
    "      fi\n"
    "      if [[ \"$key\" == \"o\" || \"$key\" == \"O\" ]]; then\n"
    "        if [[ \"$OTA_SUB\" == \"1\" ]]; then\n"
    "          curl -X POST -s http://$HOST/ota/disable\n"
    "          echo 'OTA Disabled.'\n"
    "          sleep 1\n"
    "        else\n"
    "          do_enable_ota\n"
    "        fi\n"
    "      fi\n"
    "    done\n"
    "  elif [[ \"$opt\" == \"c\" || \"$opt\" == \"C\" ]]; then\n"
    "    curl -X POST -s http://$HOST/clear-logs\n"
    "    sleep 1.5\n"
    "  elif [[ \"$opt\" == \"o\" || \"$opt\" == \"O\" ]]; then\n"
    "    if [[ \"$OTA_ON\" == \"1\" ]]; then\n"
    "      curl -X POST -s http://$HOST/ota/disable\n"
    "      echo 'OTA Disabled.'\n"
    "      sleep 1.5\n"
    "    else\n"
    "      do_enable_ota\n"
    "    fi\n"
    "  elif [[ \"$opt\" == \"r\" || \"$opt\" == \"R\" ]]; then\n"
    "    curl -X POST -s http://$HOST/reboot\n"
    "    exit 0\n"
    "  fi\n"
    "done\n",
    host.c_str(), hasKey
  );
  return String(buf.get());
}
